{
    title: 'SNFC Herp List',
    items:
    {  
      Salamanders:[      
        {family: "Ambystomatidae", name: "	Long-toed Salamander", genus: "	Ambystoma	macrodactylum	", img:"../img/Ambystoma_macrodactylum.jpeg" },
        {family: "Salamandridae", name: "	California Newt", genus: "	Taricha	torosa	", img:"../img/Taricha_torosa.jpeg"},
        {family: "Plethodontidae", name: "	Ensatina", genus: "	Ensatina	eschscholtzii	", img:"../img/Ensatina_eschscholtzii.jpeg" },
        {family: "Plethodontidae", name: "	California Slender Salamander", genus: "	Batrachoseps	attenuatus	" , img:"../img/Batrachoseps_attenuatus.jpeg"},
        {family: "Plethodontidae", name: "	Mt. Lyell Salamander", genus: "	Hydromantes	platycephalus	" , img:"../img/Hydromantes_platycephalus.jpeg"}
        ],
      Frogs:[
        {family: "Bufonidae", name: "	Western Toad", genus: "	Bufo	boreas	", img:"../img/Bufo_boreas.jpeg" },
        {family: "Hylidae", name: "	Pacific Treefrog", genus: "	Pseudacris	sierra" , img:"../img/Pseudacris_sierra.jpeg"},
        {family: "Ranidae", name: "	Red-legged Frog", genus: "	Rana	aurora	" , img:"../img/Rana_aurora.jpeg"},
        {family: "Ranidae", name: "	Foothill Yellow-legged Frog", genus: "	Rana	boylei	" , img:"../img/Rana_boylii.jpeg"},
        {family: "Ranidae", name: "	Mountan Yellow-legged Frog", genus: "	Rana	muscosa	", img:"../img/Rana_muscosa.jpeg" },
        {family: "Ranidae", name: "	Leopard Frog", genus: "	Rana	pipiens	" , img:"../img/Rana_pipiens.jpeg"},
        {family: "Ranidae", name: "	Bullfrog", genus: "	Rana	catesbeianus	" , img:"../img/Rana_catesbeianus.jpeg"}
        ],
      Turtles:[
        {family: "Emydidae", name: "	Western Pond Turtle", genus: "	Actinemys	marmorata	" , img:"../img/Actinemys_marmorata.jpeg"}
        ],
      Lizards:[
        {family: "Phrynosomatidae", name: "	Western Fence Lizard", genus: "	Sceloporus	occidentalis" , img:"../img/Sceloporus_occidentalis.jpeg"},	
        {family: "Phrynosomatidae", name: "	Sagebrush Lizard", genus: "	Sceloporus	graciosus	" , img:"../img/Sceloporus_graciosus.jpeg"},
        {family: "Phrynosomatidae", name: "	Side-blotched Lizard", genus: "	Uta	stansburiana	" , img:"../img/Uta_stansburiana.jpeg"},
        {family: "Phrynosomatidae", name: "	Coast Horned Lizard", genus: "	Phrynosoma	blainvillii" , img:"../img/Phrynosoma_blainvillii.jpeg"},
        {family: "Phrynosomatidae", name: "	Desert Horned Lizard", genus: "	Phrynosoma	platyrhinos	" , img:"../img/Phrynosoma_platyrhinos.jpeg"},
        {family: "Scincidae", name: "	Western Skink	", genus: "Plestiodon	placerensis	" , img:"../img/Plestiodon_placerensis.jpeg"},
        {family: "Scincidae", name: "	Gilbert's Skink", genus: "	Plestiodon	gilberti	" , img:"../img/Plestiodon_gilberti.jpeg"},
        {family: "Teiidae", name: "	Western Whiptail", genus: "	Aspidoscelis	tigris" , img:"../img/Aspidoscelis_tigris.jpeg"},
        {family: "Anguidae", name: "	Southern Alligator Lizard", genus: "	Elgaria	multicarinata	" , img:"../img/Elgaria_multicarinata.jpeg"},
        {family: "Anguidae", name: "	Northern Alligator Lizard", genus: "	Elgaria	coerulea	" , img:"../img/Elgaria_coerulea.jpeg"}
        ],
      Snakes:[  
        {family: "Boidae", name: "	Rubber Boa", genus: "	Charina	bottae	" , img:"../img/Charina_bottae.jpeg"},
        {family: "Colubridae", name: "	Ringneck Snake", genus: "	Diadophis	punctatus	" , img:"../img/Diadophis_punctatus.jpeg"},
        {family: "Colubridae", name: "	Sharp-tailed Snake", genus: "	Contia	tenuis	" , img:"../img/Contia_tenuis.jpeg"},
        {family: "Colubridae", name: "	Racer	", genus: "	Coluber constrictor	" , img:"../img/Coluber_constrictor.jpeg"},
        {family: "Colubridae", name: "	Striped Racer", genus: "	Masticophis	lateralis	" , img:"../img/Masticophis_lateralis.jpeg"},
        {family: "Colubridae", name: "	Striped Whipsnake", genus: "	Masticophis	taeniatus	", img:"../img/Masticophis_taeniatus.jpeg" },
        {family: "Colubridae", name: "	Western Patch-nosed Snake", genus: "	Salvadora	hexalepis" , img:"../img/Salvadora_hexalepis.jpeg"},	
        {family: "Colubridae", name: "	Gopher Snake", genus: "	Pituophis	catenifer" , img:"../img/Pituophis_catenifer.jpeg"},
        {family: "Colubridae", name: "	Common Kingsnake", genus: "	Lampropeltis	getula" , img:"../img/Lampropeltis_getula.jpeg"},
        {family: "Colubridae", name: "", name: "	Mountain Kingsnake", genus: "	Lampropeltis	zonata	" , img:"../img/Lampropeltis_zonata.jpeg"},
        {family: "Colubridae", name: "	Long-nosed Snake", genus: "	Rhinocheilus	lecontei	" , img:"../img/Rhinocheilus_lecontei.jpeg"},
        {family: "Colubridae", name: "	Common Garter Snake", genus: "	Thamnophis	sirtalis	" , img:"../img/Thamnophis_sirtalis.jpeg"},
        {family: "Colubridae", name: "	Western Terrestrial Garder Snake", genus: "	Thamnophis	elegans	" , img:"../img/Thamnophis_elegans.jpeg"},
        {family: "Colubridae", name: "	Western Aquatic Garter Snake", genus: "	Thamnophis	couchi	" , img:"../img/Thamnophis_couchii.jpeg"},
        {family: "Colubridae", name: "	Night Snake", genus: "	Hypsiglena	torquata	" , img:"../img/Hypsiglena_torquata.jpeg"},
        {family: "Viperidae", name: "	Western Rattlesnake", genus: "	Crotalus lutosis	" , img:"../img/Crotalus_lutosus.jpeg"}
        ]
   },
   allItems:
   [   {family: "Ambystomatidae", name: "	Long-toed Salamander", genus: "	Ambystoma	macrodactylum	", img:"../img/Ambystoma_macrodactylum.jpeg" },
        {family: "Salamandridae", name: "	California Newt", genus: "	Taricha	torosa	", img:"../img/Taricha_torosa.jpeg"},
        {family: "Plethodontidae", name: "	Ensatina", genus: "	Ensatina	eschscholtzii	", img:"../img/Ensatina_eschscholtzii.jpeg" },
        {family: "Plethodontidae", name: "	California Slender Salamander", genus: "	Batrachoseps	attenuatus	" , img:"../img/Batrachoseps_attenuatus.jpeg"},
        {family: "Plethodontidae", name: "	Mt. Lyell Salamander", genus: "	Hydromantes	platycephalus	" , img:"../img/Hydromantes_platycephalus.jpeg"},
        {family: "Bufonidae", name: "	Western Toad", genus: "	Bufo	boreas	", img:"../img/Bufo_boreas.jpeg" },
        {family: "Hylidae", name: "	Pacific Treefrog", genus: "	Pseudacris	sierra" , img:"../img/Pseudacris_sierra.jpeg"},
        {family: "Ranidae", name: "	Red-legged Frog", genus: "	Rana	aurora	" , img:"../img/Rana_aurora.jpeg"},
        {family: "Ranidae", name: "	Foothill Yellow-legged Frog", genus: "	Rana	boylei	" , img:"../img/Rana_boylii.jpeg"},
        {family: "Ranidae", name: "	Mountan Yellow-legged Frog", genus: "	Rana	muscosa	", img:"../img/Rana_muscosa.jpeg" },
        {family: "Ranidae", name: "	Leopard Frog", genus: "	Rana	pipiens	" , img:"../img/Rana_pipiens.jpeg"},
        {family: "Ranidae", name: "	Bullfrog", genus: "	Rana	catesbeianus	" , img:"../img/Rana_catesbeianus.jpeg"},
        {family: "Turtles	Emydidae", name: "	Western Pond Turtle", genus: "	Actinemys	marmorata	" , img:"../img/Actinemys_marmorata.jpeg"},
        {family: "Phrynosomatidae", name: "	Western Fence Lizard", genus: "	Sceloporus	occidentalis" , img:"../img/Sceloporus_occidentalis.jpeg"},	
        {family: "Phrynosomatidae", name: "	Sagebrush Lizard", genus: "	Sceloporus	graciosus	" , img:"../img/Sceloporus_graciosus.jpeg"},
        {family: "Phrynosomatidae", name: "	Side-blotched Lizard", genus: "	Uta	stansburiana	" , img:"../img/Uta_stansburiana.jpeg"},
        {family: "Phrynosomatidae", name: "	Coast Horned Lizard", genus: "	Phrynosoma	blainvillii" , img:"../img/Phrynosoma_blainvillii.jpeg"},
        {family: "Phrynosomatidae", name: "	Desert Horned Lizard", genus: "	Phrynosoma	platyrhinos	" , img:"../img/Phrynosoma_platyrhinos.jpeg"},
        {family: "Scincidae", name: "	Western Skink	", genus: "Plestiodon	placerensis	" , img:"../img/Plestiodon_placerensis.jpeg"},
        {family: "Scincidae", name: "	Gilbert's Skink", genus: "	Plestiodon	gilberti	" , img:"../img/Plestiodon_gilberti.jpeg"},
        {family: "Teiidae", name: "	Western Whiptail", genus: "	Aspidoscelis	tigris" , img:"../img/Aspidoscelis_tigris.jpeg"},
        {family: "Anguidae", name: "	Southern Alligator Lizard", genus: "	Elgaria	multicarinata	" , img:"../img/Elgaria_multicarinata.jpeg"},
        {family: "Anguidae", name: "	Northern Alligator Lizard", genus: "	Elgaria	coerulea	" , img:"../img/Elgaria_coerulea.jpeg"},
        {family: "Boidae", name: "	Rubber Boa", genus: "	Charina	bottae	" , img:"../img/Charina_bottae.jpeg"},
        {family: "Colubridae", name: "	Ringneck Snake", genus: "	Diadophis	punctatus	" , img:"../img/Diadophis_punctatus.jpeg"},
        {family: "Colubridae", name: "	Sharp-tailed Snake", genus: "	Contia	tenuis	" , img:"../img/Contia_tenuis.jpeg"},
        {family: "Colubridae", name: "	Racer	", genus: "	Coluber constrictor	" , img:"../img/Coluber_constrictor.jpeg"},
        {family: "Colubridae", name: "	Striped Racer", genus: "	Masticophis	lateralis	" , img:"../img/Masticophis_lateralis.jpeg"},
        {family: "Colubridae", name: "	Striped Whipsnake", genus: "	Masticophis	taeniatus	", img:"../img/Masticophis_taeniatus.jpeg" },
        {family: "Colubridae", name: "	Western Patch-nosed Snake", genus: "	Salvadora	hexalepis" , img:"../img/Salvadora_hexalepis.jpeg"},	
        {family: "Colubridae", name: "	Gopher Snake", genus: "	Pituophis	catenifer" , img:"../img/Pituophis_catenifer.jpeg"},
        {family: "Colubridae", name: "	Common Kingsnake", genus: "	Lampropeltis	getula" , img:"../img/Lampropeltis_getula.jpeg"},
        {family: "Colubridae", name: "", name: "	Mountain Kingsnake", genus: "	Lampropeltis	zonata	" , img:"../img/Lampropeltis_zonata.jpeg"},
        {family: "Colubridae", name: "	Long-nosed Snake", genus: "	Rhinocheilus	lecontei	" , img:"../img/Rhinocheilus_lecontei.jpeg"},
        {family: "Colubridae", name: "	Common Garter Snake", genus: "	Thamnophis	sirtalis	" , img:"../img/Thamnophis_sirtalis.jpeg"},
        {family: "Colubridae", name: "	Western Terrestrial Garder Snake", genus: "	Thamnophis	elegans	" , img:"../img/Thamnophis_elegans.jpeg"},
        {family: "Colubridae", name: "	Western Aquatic Garter Snake", genus: "	Thamnophis	couchi	" , img:"../img/Thamnophis_couchii.jpeg"},
        {family: "Colubridae", name: "	Night Snake", genus: "	Hypsiglena	torquata	" , img:"../img/Hypsiglena_torquata.jpeg"},
        {family: "Viperidae", name: "	Western Rattlesnake", genus: "	Crotalus lutosis	" , img:"../img/Crotalus_lutosus.jpeg"}
   ]}